### ISSUE TITLE
Fill out the README.md with more information about the app

### ISSUE THREAD

**Issue by trystant** [Githubbubber/castlegamingapp#1]
While it might be too late to write the README.md first as described in [Readme Driven Development](http://tom.preston-werner.com/2010/08/23/readme-driven-development.html), there is still a lot of information about the project that could be in the README, such as 

>  For the gaming tournament collective Castle Gaming, I built a fully developed Node JS app deployed on the Heroku hosting platform. It uses APIs that I’ve been interested in working with for a while: The New York Times, Twitch, and GiantBomb. The ease of building the app’s layout using the Skeleton css framework gave me the freedom to concentrate on the content without worrying about how it looked on mobile devices.

There are a few [README.md templates][https://gist.github.com/trystant/d4c593a23336c4e12e9a796abe1b2457] you can use for inspiration on what you want to put in that documentation.

**Comment by Githubbubber** [comment]
I updated it as best I can. I did not create any tests for the application since I'm not too knowledgeable in this area. Do you think I should do tests and such before I start applying to apprenticeships?
